fruits=["orange","apple","strawberry"]
print(fruits)
fruits.append("blueberry")
print(fruits)
fruits.insert(2,"blackberry")
print(fruits)
fruits.remove("orange")
print(fruits)
fruits.reverse()
print(fruits)
fruits.pop(1)
print(fruits)

print(fruits[2])
fruits.append("pear")
fruits.append("dragon fruit")
fruits.append("pinapple")
fruits.sort()
print(fruits)
